Repository SoftUni-Internal/OpenJudgeSystem, pull requests merged in 2022-10, with the labels that each got.

#515 Fixed moving page bug when there is only 1 page available in /contests
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/ContestsPage.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/ContestsPage.tsx
Labels: Bug

#520 Added test GH Action
  .github/workflows/admin-build.yml
  .github/workflows/ui-build.yml
  Docker/Dockerfile.administration
  Docker/Dockerfile.ui
  Servers/UI/OJS.Servers.Ui/ClientApp/.eslintrc.js
  Servers/UI/OJS.Servers.Ui/ClientApp/craco.config.js
  Servers/UI/OJS.Servers.Ui/ClientApp/package.json
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/Diff.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/problem-submission-details/ProblemSubmissionDetails.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/problem-submission-details/ProblemSubmissionDetails.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/modals/confirm/ConfirmModal.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/modals/confirm/ConfirmModal.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/header-greeting/HeaderGreeting.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-header/HomeHeaderInfo.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-header/HomeHeaderInfo.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-header/HomeHeaderVideo.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-header/HomeHeaderVideo.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submission/ProblemSubmission.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submission/ProblemSubmission.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/profile/profile-submissions/ProfileSubmisssions.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/index.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/login/LoginPage.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/profile/ProfilePage.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/react-app-env.d.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/src/services/auth-service.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/yarn.lock
  docker-compose.yml
Labels: WIP

#527 Implemented consistent titles on categories, strategies, and contest cards titles
  Servers/UI/OJS.Servers.Ui/ClientApp/src/common/tree-types.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/src/common/types.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-categories/ContestCategories.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/ExpandMoreIcon.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/RightArrowIcon.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/contests/contest-filter-utils.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/use-contest-categories-breadcrumb.tsx
Labels: Enhancement

#532 Contest page category tree and contest cards fixes
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.module.scss
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
Labels: Bug, Enhancement
