Repository SoftUni-Internal/OpenJudgeSystem, pull requests merged in 2023-06, with the labels that each got.

#667 Validate author solutions
  Open Judge System/Data/OJS.Data.Models/Contest.cs
  Open Judge System/Services/OJS.Services/Data/Contests/ContestsDataService.cs
  Open Judge System/Services/OJS.Services/Data/Contests/IContestsDataService.cs
  Open Judge System/Services/OJS.Services/Data/Submissions/Models/SubmissionTypeForProblem.cs
  Open Judge System/Services/OJS.Services/OJS.Services.csproj
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/ViewModels/ContestAdministration.Designer.cs
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/ViewModels/ContestAdministration.bg.Designer.cs
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/ViewModels/ContestAdministration.bg.resx
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/ViewModels/ContestAdministration.resx
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/Views/Partials/ContestEditor.Designer.cs
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/Views/Partials/ContestEditor.bg.designer.cs
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/Views/Partials/ContestEditor.bg.resx
  Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Administration/Contests/Views/Partials/ContestEditor.resx
  Open Judge System/Web/OJS.Web/Areas/Administration/Controllers/ContestsController.cs
  Open Judge System/Web/OJS.Web/Areas/Administration/ViewModels/Contest/ContestAdministrationViewModel.cs
  Open Judge System/Web/OJS.Web/Areas/Administration/Views/Contests/_ContestEditor.cshtml
  Open Judge System/Web/OJS.Web/Controllers/BaseController.cs
Labels: Legacy Judge

#706 Switched additional authentication cookies with user loaded in state
  Servers/Administration/OJS.Servers.Administration/Controllers/AccountController.cs
  Servers/Infrastructure/OJS.Servers.Infrastructure/Extensions/HttpExtensions.cs
  Servers/Infrastructure/OJS.Servers.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  Servers/UI/OJS.Servers.Ui/ClientApp/src/App.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/common/types.ts
  Servers/UI/OJS.Servers.Ui/ClientApp/src/components/header-greeting/HeaderGreeting.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/use-auth.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/use-urls.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/nav/PageNav.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/login/LoginPage.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/register/RegisterPage.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/shared/make-private.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/submission-details/SubmissionDetailsPage.tsx
  Servers/UI/OJS.Servers.Ui/ClientApp/src/services/user-cookies-service.tsx
  Servers/UI/OJS.Servers.Ui/Controllers/AccountController.cs
  Servers/UI/OJS.Servers.Ui/Controllers/Api/UsersController.cs
  Services/UI/OJS.Services.Ui.Business/IUsersBusinessService.cs
  Services/UI/OJS.Services.Ui.Business/Implementations/UsersBusinessService.cs
  Services/UI/OJS.Services.Ui.Models/Users/RoleServiceModel.cs
  Services/UI/OJS.Services.Ui.Models/Users/UserAuthInfoServiceModel.cs
Labels: Alpha Judge

#722 Fixed submission details page not loading
  Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/submission-details/SubmissionDetailsPage.tsx
Labels: Bug, Alpha Judge
